name: Build Mod
on: [push, pull_request]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/34.0.0" >> $GITHUB_PATH
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build mod jar
      run: |
        chmod +x ./gradlew
        ./gradlew deploy
    - name: Upload built java jar file
      uses: actions/upload-artifact@v4
      with:
        name: java-2.0.0
        path: java/build/libs/java-2.0.0.jar
    - name: Upload built js jar file
      uses: actions/upload-artifact@v4
      with:
        name: js-2.0.0
        path: js/build/libs/js-2.0.0.jar
